[tool.poetry]
name = "pythonbook"
version = "0.1.0"
description = ""
authors = ["13002457275 <4448445@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
