version: "3.8"

services:
  web:
    build: .
    image: real-time-charts-with-fastapi
    command: uvicorn application:application --reload --host 0.0.0.0 --port 5000
    volumes:
      - .:/code
    ports:
      - "127.0.0.1:5000:5000"